version: '3'
services:
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    networks:
      - my_network

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    environment:
      - DOMAIN=your_domain.com
      - EMAIL=your_email@gmail.com
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    expose:
      - 3001
    networks:
      - my_network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/baituan
      - JWT_SECRET=
      - API_PORT=3001
      - GLOT_IO_API_KEY=
    depends_on:
      - mongodb

networks:
  my_network:
