FROM node:18

RUN apt-get install -y caddy

WORKDIR /app

RUN cd /app/frontend && yarn install --production && yarn build

ENV MONGODB_URI="mongodb://localhost:27017/baituan"
ENV JWT_SECRET=""
ENV API_PORT=3001
ENV GLOT_IO_API_KEY=""

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
EXPOSE 443

CMD caddy run --config /etc/caddy/Caddyfile
