version: '3'
services:
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    networks:
      - my_network
    volumes:
      - mongodb_data:/data/db

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    environment:
      - DOMAIN=your_domain.com
      - EMAIL=your_email@gmail.com
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    volumes:
      - caddy_data:/root/.local/share/caddy
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    expose:
      - 3001
    networks:
      - my_network
    environment:
      - TZ=Asia/Shanghai
      - MONGODB_URI=mongodb://mongodb:27017/baituan
      - JWT_SECRET=
      - API_PORT=3001
      - GLOT_IO_API_KEY=
      - ABLY_API_KEY=
      - CLOUDFLARE_API_KEYS=
    depends_on:
      - mongodb
    volumes:
      - ./game:/app/game

networks:
  my_network:

volumes:
  mongodb_data:
  caddy_data: